### ISSUE TITLE
Issue write to med format from meshio mesh

### ISSUE THREAD

**Issue by valedy** [nschloe/meshio#965]
Hello,
I'm working with the python module. I've created a 3d surface mesh in meshio format and I would like to write it in MED format.
An extract of my code is bellow:
``` python
import meshio
import numpy as np

vtk_to_meshio_types = {
5: "triangle",
9: "quad",
10: "tetra",
12: "hexahedron"
}

vtktypes_to_nb_of_pts = {
5: 3,
9: 4,
10: 4,
12: 8
}

def create_meshio_mesh(pt_coords, connectivity, offsets, cell_types):
    # points
    mio_points=np.array([np.array(c) for c in pt_coords])
    # cells
    mio_cells = list()
    for i in range(len(cell_types)):
        nb_of_pts = vtktypes_to_nb_of_pts[cell_types[i]]
        pid_list = list()
        for j in range(nb_of_pts):
            pos = int(offsets[i] + j)
            pid_list.append(int(connectivity[pos]))
        mio_cells.append((vtk_to_meshio_types[int(cell_types[i])], np.array([pid_list])))
    mio_mesh = meshio.Mesh(points=mio_points, cells=mio_cells)
    return mio_mesh

pt_coords = [ [0.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0], [1.0, 0.0, 0.0] ]
connectivity = [0, 1, 2, 3, 1, 2]
offsets = [0,3,6]
cell_types =[5,5]

# create meshio mesh
mio_surface = create_meshio_mesh(
pt_coords=pt_coords,
connectivity=connectivity,
offsets=offsets,
cell_types=cell_types)
# Initialize pressure field
data = list()
for i in range(len(cell_types)):
    data.append(1)
pressure_data = np.array(data)
mio_surface.cell_data["pressure"] = pressure_data
# Write surface mesh on disk
file_name = "test.med"
meshio.write(filename=file_name, mesh=mio_surface, file_format="med")
```

I'm being very confused because if I change the file extension and the file_format to "vtk" the mesh is written correctly. But with "med" format the written mesh as the points but only 1 cell. Does someone have any hints?
Thanks in advance,
V.

**Comment by nschloe** [comment]
This uses code from `mio_tools` that you did not disclose. It's impossible to say what's wrong. Feel free to reopen with a complete, minimal example.

**Comment by valedy** [comment]
Ok, I post a new one

**Comment by valedy** [comment]
Hi nschloe, how do I reopen the issue ?

**Comment by nschloe** [comment]
You click the "Reopen and comment" button.

**Comment by valedy** [comment]
I only see the "comment" button.. No  "reopen and comment"  . info : my github account is new (jsut created before opening the issue)

**Comment by nschloe** [comment]
Ah I see. Apparently you can only reopen issues if you closed them yourself. In this case, just comment.

**Comment by valedy** [comment]
Ok so, is the post suffisant to test my issue? If yes, can you reopen it ?

**Comment by nschloe** [comment]
If it fulfills the standards, yes.

**Comment by nschloe** [comment]
I tried running the code and got
```
  File "e.py", line 20
    mio_points=np.array([np.array(c) for c in pt_coords])
    ^
IndentationError: expected an indented block
```

**Comment by valedy** [comment]
Oh yeah sorry I forgot some indent

**Comment by nschloe** [comment]
Okay, can you make _one_ code block please?

**Comment by valedy** [comment]
done

**Comment by nschloe** [comment]
Still not working:
```
NameError: name 'mio_tools' is not defined
```
Unfortunately, I don't have time for this now. Will come back some other day. Just make sure that the example is complete.

**Comment by valedy** [comment]
Corrected, no problem, thanks for your time

**Comment by keurfonluu** [comment]
Here is your error:

```python
mio_surface.cell_data["pressure"] = pressure_data
```

`pressure_data` is a one-dimensional array of size 2, while `meshio` expects a list of arrays with sizes consistent with `cells`.
Not sure why it works with VTK, though.

However, I am far more concerned by the complexity of your code. The mesh you want to create can be generated using this simple code:

```python
import numpy
import meshio

points = numpy.array(
    [
        [0.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.0, 0.0, 1.0],
        [1.0, 0.0, 0.0],
    ]
)
cells = [("triangle", numpy.array([[0, 1, 2], [3, 1, 2]]))]
cell_data = {"pressure": [numpy.ones(2)]}
meshio.write_points_cells("test.med", points, cells, cell_data=cell_data)
```

**Comment by valedy** [comment]
Thank you but if I change the pressure_data to a list of numpy array it's still not working with the MED format with same error, does it work on your system ? Note that with the vtk format the pressure field is correctly initialized now. I've just changed this line : 
```python
mio_surface.cell_data = {"pressure" : [np.ones(len(cell_types))]}
```
Here is the error message : 
```
Traceback (most recent call last):
  File "test.py", line 52, in <module>
    meshio.write(filename=file_name, mesh=mio_surface, file_format="med")
  File "/home/valentin/.conda/envs/AsterAndCICLONE/lib/python3.7/site-packages/meshio/_helpers.py", line 144, in write
    return writer(filename, mesh, **kwargs)
  File "/home/valentin/.conda/envs/AsterAndCICLONE/lib/python3.7/site-packages/meshio/med/_med.py", line 272, in write
    med_cells = cells_group.create_group(med_type)
  File "/home/valentin/.conda/envs/AsterAndCICLONE/lib/python3.7/site-packages/h5py/_hl/group.py", line 65, in create_group
    gid = h5g.create(self.id, name, lcpl=lcpl, gcpl=gcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 162, in h5py.h5g.create
ValueError: Unable to create group (name already exists)
```
The complexity of the code is because it has to deal with any kind of surface mesh and I have only information on points coordinates, connectivity, offsets and vtk cells types. It's integrated in a Fluid-Structure interaction computation code

**Comment by keurfonluu** [comment]
Your code creates two cellblocks of type `"triangle"` of one cell:

```python
cells = [
    ("triangle", numpy.array([[0, 1, 2]]))),
    ("triangle", numpy.array([[3, 1, 2]]))),
]
```

so `cell_data` should be a list of two arrays:

```python
cell_data = {"pressure": [[1.0], [1.0]]}
```

Anyway, multiple cell blocks with the same type does not seem to be supported by the MED format (`meshio` throws an error), you should gather all triangles in the same cell block, such that:

```python
cells = [("triangle", numpy.array([[0, 1, 2], [3, 1, 2]]))]
cell_data = {"pressure": [[1.0, 1.0]]}
```

Concerning the complexity, I was also referring to how you treat your arrays which looks unconventional. Anyway, I would strongly suggest you to look at how the function [`pyvista.save_meshio`](https://github.com/pyvista/pyvista/blob/919c4d184ff62218d8d6a1f08d8446aa51633063/pyvista/utilities/fileio.py#L374) is implemented as it deals with the same kind of information.

**Comment by valedy** [comment]
Hello nschloe, 
Sorry for the late feed back. I tried to write the mesh as pyvista do it (i.e. with write_points_cells method) but I get the same error as before, i.e. "Unable to create group". 
I've had a small heard of the pyvista module before and I think that's more convivient to use direcly pyvista for my study. Thanks for remembering me the existence of this library! So now I use the method "save_meshio" from pyvista and no problem occurs. 
But the original problem is still bother me..
